using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodingMania.LeetCodeQuestions.String.Easy
{
    /*
     you are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
     */
    class FindTheDifference
    {
        public char FindTheDifferenceMethod(string s, string t)
        {
            int sumS = 0, sumT = 0;

            foreach (char c in s)
                sumS += c;

            foreach (char c in t)
                sumT += c;

            return (char)(sumT - sumS);
        }
    }
}
